#!/bin/bash

export WINIT_HIDPI_FACTOR=1

# Runs a program unless that program is already running
function conditional_run {
    local program_name=$1

    ps_result=$(ps aux \
        | grep "${program_name}" \
        | grep -v "grep" \
        | wc -l
        )
    if [ $ps_result -eq 0 ]; then
        echo "Running $program_name"
        `$program_name` &
    else
        echo "$program_name already running"
    fi
}

export MOZ_USE_XINPUT2=1

export IS_TABLET=0

echo 'export RIGHT_PADDING=27' > /tmp/wm_settings
echo 'export BOTTOM_PADDING=3' >> /tmp/wm_settings
echo 'export REST_PADDING=3' >> /tmp/wm_settings

source /tmp/wm_settings


OLD_PATH=$PATH
PATH=$PATH:$HOME/bin/:$HOME/.cargo/bin

#Restart all our programs
# pkill sxhkd
# pkill tint2
# pkill xfce4-panel
# pkill xfce4-power-manager
# pkill volumeicon
# pkill nm-applet
# # pkill compton;
# pkill redshift
# pkill wpmServer.py
# pkill blueman-applet
# pkill rspwm
# pkill touchegg
#wp k #Kill the wallpaper manager

CONFIG_DIR="/home/frans/.config/bspwm"

#Starting required stuff
# compton --config ~/.config/compton/comptonrc & #Transparent windows
#feh --bg-fill --no-xinerama /home/frans/Pictures/wallpapers/current.png #set background
#feh --bg-fill /home/frans/Pictures/wallpapers/current.png #set background
./wallpaper

echo "Bottom padding ${BOTTOM_PADDING}, right padding: ${RIGHT_PADDING}"

bspc config border_width       3
bspc config window_gap         4

~/.config/bspwm/configure_padding

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config auto_cancel true
bspc config normal_border_color "#000000"
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config sinngle_monocle true

#change working directory to allow relative paths in python and bash
cd $CONFIG_DIR
./startup.py #Setup everything python based
#./pypanel.py #Create the panel


#Monitor layout is handled by python script
#bspc monitor -d I II III IV V VI VII VIII IX X

pkill tint2
pkill xfce4-panel
if [ $IS_TABLET -eq 1 ]; then
    #xfce4-panel --disable-wm-check &
    echo "tablet mode, no sys tray"
else
    tint2 &
fi

# Reload xresources
xrdb ~/.Xresources
# Run autostart configured in ~/bin
autostart
# Set the keyboard layout
setxkbmap us -variant altgr-intl -option caps:ctrl_modifier

#Reset the working directory
cd

conditional_run konsoletheme
conditional_run xfce4-power-manager
conditional_run volumeicon
conditional_run nm-applet
conditional_run redshift
conditional_run blueman-applet
conditional_run /home/frans/.cargo/bin/rspwm
conditional_run touchegg
conditional_run xfce4-clipman
conditional_run sxhkd
conditional_run indicator-kdeconnect

# Move tint2 behind fullscreen windows
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n tint2)


#Enable if something goes wrong
#xfce4-terminal &

PATH=$OLD_PATH


