#! /bin/bash

#Restart all our programs
pkill tint2
pkill xfce4-power-manager
pkill volumeicon
pkill nm-applet
pkill compton;

CONFIG_DIR="/home/frans/.config/bspwm"

#Starting required stuff
compton --config ~/.config/compton/comptonrc & #Transparent windows
#feh --bg-fill /home/frans/Pictures/wallpapers/city1.jpg #set background
feh --bg-fill --no-xinerama /home/frans/Pictures/wallpapers/current.png #set background

bspc config border_width        1
bspc config window_gap         6

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config auto_cancel true

#change working directory to allow relative paths in python and bash
cd $CONFIG_DIR
./startup.py #Setup everything python based
./pypanel.py #Create the panel


#Monitor layout is handled by python script
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


tint2 &
#xsetroot -cursor_name left_ptr
xfce4-power-manager &
volumeicon &
nm-applet &

#Reset the working directory
cd
