#!/bin/bash

# Read the current setings
source /tmp/wm_settings

# Check if the user has requested fullscreen mode
if [ $1 = "df" ]; then
    export RIGHT_PADDING=0
    export BOTTOM_PADDING=0
    export REST_PADDING=0
fi


# Tell bspc about the updates
bspc config right_padding $RIGHT_PADDING
bspc config left_padding $REST_PADDING
bspc config top_padding $REST_PADDING
bspc config bottom_padding $BOTTOM_PADDING

xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n tint2)
