#!/bin/bash
scrot /tmp/screenshot.png
#convert /tmp/screenshot.png -blur 0x3 /tmp/screenshotblur.png
convert /tmp/screenshot.png -filter box -scale 20% /tmp/screenshotblur.png
convert /tmp/screenshotblur.png -filter box -scale 500% /tmp/screenshotblur.png
i3lock -i /tmp/screenshotblur.png
